# Generated by Django 2.2.5 on 2019-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
