# Generated by Django 2.2.5 on 2019-09-23 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_weeklyreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='week_number',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='duration_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 6, 4, 4, 464353, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='duration_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 6, 4, 14, 135628, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='t_name',
            field=models.CharField(default='kaka', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='report',
            field=models.FileField(null=True, upload_to=tasks.models.WeeklyReport.report_file_path),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
