# Generated by Django 2.2.5 on 2019-09-23 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20190923_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='head',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='head', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate', to=settings.AUTH_USER_MODEL),
        ),
    ]
